name: flutter_camera
description: Demo app showing capabilities and limitations of using camera in Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  camera: ^0.5.6+3
  device_info: ^0.4.1+1
  path_provider: ^1.4.2
  path: ^1.6.4
  carousel_slider: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
